### ISSUE TITLE
Duplicate Symbol when running with SocketRocket

### ISSUE THREAD

**Issue by AdrianMint** [SocketMobile/cocoapods-capture#18]
I have a project which runs SocketRocket and SKTCaptureObjC. After updating to 1.2.187 (from 1.2.53) i got several duplicate symbol errors in my project. 

To reproduce the error, run https://github.com/SocketMobile/capturesingleentry-ios with the pod:
```
target 'SingleEntry'
  pod 'SKTCaptureObjC'
  pod 'SocketRocket'
```

Cocoapods version: 1.10.0
Xcode Version:  12.2

**Comment by EricGlaenzer** [comment]
Hi @AdrianMint ,
Sorry to read about your issue with SocketRocket. We do have by mistake let the SocketRocket slipped into this release. 
We are going to remove it and release again the cocoapods. Stay tuned...

**Comment by EricGlaenzer** [comment]
Hi @AdrianMint ,
The version 1.3.3 should fix your issue. Sorry for the inconvenience and thank you for being patient.
